apiVersion: addons.managed.openshift.io/v1alpha1
kind: Addon
metadata:
  name: example-addon
spec:
  displayName: An amazing example addon!
  namespaces:
  - name: foo
  - name: collision
  - name: bar
  - name: additional
  - name: to-be-removed
  install:
    type: OwnNamespace
    ownNamespace:
      namespace: "foo"
      # This is the operathub catalog source because (at least for now)
      # we don't have an example catalog image to develop against
      catalogSourceImage: quay.io/operatorhubio/catalog:latest
      packageName: "minio-operator"
